// src/App.tsx
import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Home from "./ui/home/Home";
import QuestsTab from "./ui/quests/QuestsTab";
import SettingsTab from "./ui/settings/SettingsTab";

const tabs = ["Home", "Quests", "Settings"] as const;
export type Tab = (typeof tabs)[number];

export default function App() {
  const [tab, setTab] = useState<Tab>("Home");
  return (
    <div className="app-root">
      <div className="flex-1 p-3">
        <AnimatePresence mode="wait">
          <motion.div
            key={tab}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -6 }}
            transition={{ duration: 0.15 }}
          >
            {tab === "Home" && <Home />}
            {tab === "Quests" && <QuestsTab />}
            {tab === "Settings" && <SettingsTab />}
          </motion.div>
        </AnimatePresence>
      </div>
      <nav className="app-nav">
        {tabs.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`tab-button ${tab === t ? "active" : ""}`}
            aria-current={tab === t ? "true" : undefined}
          >
            {t}
          </button>
        ))}
      </nav>
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { fade } from "svelte/transition";
  import Home from "./ui/home/Home.svelte";
  import QuestsTab from "./ui/quests/QuestsTab.svelte";
  import SettingsTab from "./ui/settings/SettingsTab.svelte";
  import { startMaintenance } from "./logic/maintenance";

  const tabs = ["Home", "Quests", "Settings"] as const;
  type Tab = (typeof tabs)[number];

  let tab: Tab = "Home";
  let stopMaintenance: (() => void) | undefined;

  onMount(() => {
    stopMaintenance = startMaintenance();
  });

  onDestroy(() => {
    stopMaintenance?.();
  });
</script>

<div class="app-root">
  <div class="app-main">
    {#if tab === "Home"}
      <div in:fade={{ duration: 150 }} out:fade={{ duration: 120 }}>
        <Home />
      </div>
    {:else if tab === "Quests"}
      <div in:fade={{ duration: 150 }} out:fade={{ duration: 120 }}>
        <QuestsTab />
      </div>
    {:else}
      <div in:fade={{ duration: 150 }} out:fade={{ duration: 120 }}>
        <SettingsTab />
      </div>
    {/if}
  </div>

  <nav class="app-nav">
    {#each tabs as t}
      <button
        class={`tab-button ${tab === t ? "active" : ""}`}
        aria-current={tab === t ? "true" : undefined}
        on:click={() => (tab = t)}
      >
        {t}
      </button>
    {/each}
  </nav>
</div>
